<div class="hero-unit">
	<h1>Welcome!</h1>
	<p>This admin panel has been generated by the FuelPHP Framework.</p>
	<p>This Media Manager is currently a <i>work in progress<i>.</p>
	<p><a class="btn primary large" href="http://docs.fuelphp.com">Read the Docs</a></p>
</div>
<div class="row">
	<div class="span4">
		<h2>Truncation</h2>
		<p>Press <a href="admin/truncate">here</a> to truncate the tables.</p>
	</div>
	<div class="span4">
		&nbsp;
	</div>
	<div class="span4">
		<h2>Stats</h2>
		<p>Files: <?php echo $files; ?></p>
		<p>Images: <?php echo $images; ?></p>
		<p>Movies: <?php echo $movies; ?></p>
		<p>Subtitles: <?php echo $subtitles; ?></p>
		<p>People: <?php echo $people; ?></p>
		<p>Directors: <?php echo $directors; ?></p>
		<p>Actors: <?php echo $actors; ?></p>
		<p>Producers: <?php echo $producers; ?></p>
	</div>
</div>